export const MenuItems =[
    {
        titel:'HOME',
        url:'/',
        cName:'nav-links'
    },
    {
        titel:'INVITATION',
        url:'#invitation',
        cName:'nav-links'
    },
    {
        titel:'OUR STORY',
        url:'#ourstory',
        cName:'nav-links'
    },
    {
        titel:'FAMILY',
        url:'#family',
        cName:'nav-links'
    },
    {
        titel:'GALLERY',
        url:'#gallary',
        cName:'nav-links'
    },
    {
        titel:'WISHES',
        url:'#sendwishes',
        cName:'nav-links'
    }
]